/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.bmq.vn.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.AuditedModel;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CtbProduct service. Represents a row in the &quot;ctb_product&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.bmq.vn.model.impl.CtbProductModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.bmq.vn.model.impl.CtbProductImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CtbProduct
 * @see com.bmq.vn.model.impl.CtbProductImpl
 * @see com.bmq.vn.model.impl.CtbProductModelImpl
 * @generated
 */
@ProviderType
public interface CtbProductModel extends AuditedModel, BaseModel<CtbProduct>,
	ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ctb product model instance should use the {@link CtbProduct} interface instead.
	 */

	/**
	 * Returns the primary key of this ctb product.
	 *
	 * @return the primary key of this ctb product
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this ctb product.
	 *
	 * @param primaryKey the primary key of this ctb product
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the product_id of this ctb product.
	 *
	 * @return the product_id of this ctb product
	 */
	public long getProduct_id();

	/**
	 * Sets the product_id of this ctb product.
	 *
	 * @param product_id the product_id of this ctb product
	 */
	public void setProduct_id(long product_id);

	/**
	 * Returns the company ID of this ctb product.
	 *
	 * @return the company ID of this ctb product
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this ctb product.
	 *
	 * @param companyId the company ID of this ctb product
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this ctb product.
	 *
	 * @return the user ID of this ctb product
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this ctb product.
	 *
	 * @param userId the user ID of this ctb product
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this ctb product.
	 *
	 * @return the user uuid of this ctb product
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this ctb product.
	 *
	 * @param userUuid the user uuid of this ctb product
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this ctb product.
	 *
	 * @return the user name of this ctb product
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this ctb product.
	 *
	 * @param userName the user name of this ctb product
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this ctb product.
	 *
	 * @return the create date of this ctb product
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this ctb product.
	 *
	 * @param createDate the create date of this ctb product
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this ctb product.
	 *
	 * @return the modified date of this ctb product
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this ctb product.
	 *
	 * @param modifiedDate the modified date of this ctb product
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the product_code of this ctb product.
	 *
	 * @return the product_code of this ctb product
	 */
	@AutoEscape
	public String getProduct_code();

	/**
	 * Sets the product_code of this ctb product.
	 *
	 * @param product_code the product_code of this ctb product
	 */
	public void setProduct_code(String product_code);

	/**
	 * Returns the product_name of this ctb product.
	 *
	 * @return the product_name of this ctb product
	 */
	@AutoEscape
	public String getProduct_name();

	/**
	 * Sets the product_name of this ctb product.
	 *
	 * @param product_name the product_name of this ctb product
	 */
	public void setProduct_name(String product_name);

	/**
	 * Returns the status of this ctb product.
	 *
	 * @return the status of this ctb product
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this ctb product.
	 *
	 * @param status the status of this ctb product
	 */
	public void setStatus(String status);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(CtbProduct ctbProduct);

	@Override
	public int hashCode();

	@Override
	public CacheModel<CtbProduct> toCacheModel();

	@Override
	public CtbProduct toEscapedModel();

	@Override
	public CtbProduct toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}