/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.bmq.vn.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.bmq.vn.model.CtbStoreType;
import com.bmq.vn.model.CtbStoreTypeModel;
import com.bmq.vn.model.CtbStoreTypeSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the CtbStoreType service. Represents a row in the &quot;ctb_store_type&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link CtbStoreTypeModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CtbStoreTypeImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CtbStoreTypeImpl
 * @see CtbStoreType
 * @see CtbStoreTypeModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class CtbStoreTypeModelImpl extends BaseModelImpl<CtbStoreType>
	implements CtbStoreTypeModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a ctb store type model instance should use the {@link CtbStoreType} interface instead.
	 */
	public static final String TABLE_NAME = "ctb_store_type";
	public static final Object[][] TABLE_COLUMNS = {
			{ "store_type_id", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "store_type_code", Types.VARCHAR },
			{ "store_type_name", Types.VARCHAR },
			{ "status", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("store_type_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("store_type_code", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("store_type_name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("status", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table ctb_store_type (store_type_id LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,store_type_code VARCHAR(75) null,store_type_name VARCHAR(75) null,status VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table ctb_store_type";
	public static final String ORDER_BY_JPQL = " ORDER BY ctbStoreType.store_type_id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY ctb_store_type.store_type_id ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.bmq.vn.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.bmq.vn.model.CtbStoreType"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.bmq.vn.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.bmq.vn.model.CtbStoreType"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.bmq.vn.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.bmq.vn.model.CtbStoreType"),
			true);
	public static final long STATUS_COLUMN_BITMASK = 1L;
	public static final long STORE_TYPE_ID_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static CtbStoreType toModel(CtbStoreTypeSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		CtbStoreType model = new CtbStoreTypeImpl();

		model.setStore_type_id(soapModel.getStore_type_id());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setStore_type_code(soapModel.getStore_type_code());
		model.setStore_type_name(soapModel.getStore_type_name());
		model.setStatus(soapModel.getStatus());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<CtbStoreType> toModels(CtbStoreTypeSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<CtbStoreType> models = new ArrayList<CtbStoreType>(soapModels.length);

		for (CtbStoreTypeSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.bmq.vn.service.util.ServiceProps.get(
				"lock.expiration.time.com.bmq.vn.model.CtbStoreType"));

	public CtbStoreTypeModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _store_type_id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setStore_type_id(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _store_type_id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CtbStoreType.class;
	}

	@Override
	public String getModelClassName() {
		return CtbStoreType.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("store_type_id", getStore_type_id());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("store_type_code", getStore_type_code());
		attributes.put("store_type_name", getStore_type_name());
		attributes.put("status", getStatus());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long store_type_id = (Long)attributes.get("store_type_id");

		if (store_type_id != null) {
			setStore_type_id(store_type_id);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String store_type_code = (String)attributes.get("store_type_code");

		if (store_type_code != null) {
			setStore_type_code(store_type_code);
		}

		String store_type_name = (String)attributes.get("store_type_name");

		if (store_type_name != null) {
			setStore_type_name(store_type_name);
		}

		String status = (String)attributes.get("status");

		if (status != null) {
			setStatus(status);
		}
	}

	@JSON
	@Override
	public long getStore_type_id() {
		return _store_type_id;
	}

	@Override
	public void setStore_type_id(long store_type_id) {
		_columnBitmask = -1L;

		_store_type_id = store_type_id;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return StringPool.BLANK;
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getStore_type_code() {
		if (_store_type_code == null) {
			return StringPool.BLANK;
		}
		else {
			return _store_type_code;
		}
	}

	@Override
	public void setStore_type_code(String store_type_code) {
		_store_type_code = store_type_code;
	}

	@JSON
	@Override
	public String getStore_type_name() {
		if (_store_type_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _store_type_name;
		}
	}

	@Override
	public void setStore_type_name(String store_type_name) {
		_store_type_name = store_type_name;
	}

	@JSON
	@Override
	public String getStatus() {
		if (_status == null) {
			return StringPool.BLANK;
		}
		else {
			return _status;
		}
	}

	@Override
	public void setStatus(String status) {
		_columnBitmask |= STATUS_COLUMN_BITMASK;

		if (_originalStatus == null) {
			_originalStatus = _status;
		}

		_status = status;
	}

	public String getOriginalStatus() {
		return GetterUtil.getString(_originalStatus);
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			CtbStoreType.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CtbStoreType toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (CtbStoreType)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CtbStoreTypeImpl ctbStoreTypeImpl = new CtbStoreTypeImpl();

		ctbStoreTypeImpl.setStore_type_id(getStore_type_id());
		ctbStoreTypeImpl.setCompanyId(getCompanyId());
		ctbStoreTypeImpl.setUserId(getUserId());
		ctbStoreTypeImpl.setUserName(getUserName());
		ctbStoreTypeImpl.setCreateDate(getCreateDate());
		ctbStoreTypeImpl.setModifiedDate(getModifiedDate());
		ctbStoreTypeImpl.setStore_type_code(getStore_type_code());
		ctbStoreTypeImpl.setStore_type_name(getStore_type_name());
		ctbStoreTypeImpl.setStatus(getStatus());

		ctbStoreTypeImpl.resetOriginalValues();

		return ctbStoreTypeImpl;
	}

	@Override
	public int compareTo(CtbStoreType ctbStoreType) {
		int value = 0;

		if (getStore_type_id() < ctbStoreType.getStore_type_id()) {
			value = -1;
		}
		else if (getStore_type_id() > ctbStoreType.getStore_type_id()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof CtbStoreType)) {
			return false;
		}

		CtbStoreType ctbStoreType = (CtbStoreType)obj;

		long primaryKey = ctbStoreType.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		CtbStoreTypeModelImpl ctbStoreTypeModelImpl = this;

		ctbStoreTypeModelImpl._setModifiedDate = false;

		ctbStoreTypeModelImpl._originalStatus = ctbStoreTypeModelImpl._status;

		ctbStoreTypeModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<CtbStoreType> toCacheModel() {
		CtbStoreTypeCacheModel ctbStoreTypeCacheModel = new CtbStoreTypeCacheModel();

		ctbStoreTypeCacheModel.store_type_id = getStore_type_id();

		ctbStoreTypeCacheModel.companyId = getCompanyId();

		ctbStoreTypeCacheModel.userId = getUserId();

		ctbStoreTypeCacheModel.userName = getUserName();

		String userName = ctbStoreTypeCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			ctbStoreTypeCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			ctbStoreTypeCacheModel.createDate = createDate.getTime();
		}
		else {
			ctbStoreTypeCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			ctbStoreTypeCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			ctbStoreTypeCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		ctbStoreTypeCacheModel.store_type_code = getStore_type_code();

		String store_type_code = ctbStoreTypeCacheModel.store_type_code;

		if ((store_type_code != null) && (store_type_code.length() == 0)) {
			ctbStoreTypeCacheModel.store_type_code = null;
		}

		ctbStoreTypeCacheModel.store_type_name = getStore_type_name();

		String store_type_name = ctbStoreTypeCacheModel.store_type_name;

		if ((store_type_name != null) && (store_type_name.length() == 0)) {
			ctbStoreTypeCacheModel.store_type_name = null;
		}

		ctbStoreTypeCacheModel.status = getStatus();

		String status = ctbStoreTypeCacheModel.status;

		if ((status != null) && (status.length() == 0)) {
			ctbStoreTypeCacheModel.status = null;
		}

		return ctbStoreTypeCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(19);

		sb.append("{store_type_id=");
		sb.append(getStore_type_id());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", store_type_code=");
		sb.append(getStore_type_code());
		sb.append(", store_type_name=");
		sb.append(getStore_type_name());
		sb.append(", status=");
		sb.append(getStatus());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(31);

		sb.append("<model><model-name>");
		sb.append("com.bmq.vn.model.CtbStoreType");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>store_type_id</column-name><column-value><![CDATA[");
		sb.append(getStore_type_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>store_type_code</column-name><column-value><![CDATA[");
		sb.append(getStore_type_code());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>store_type_name</column-name><column-value><![CDATA[");
		sb.append(getStore_type_name());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>status</column-name><column-value><![CDATA[");
		sb.append(getStatus());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = CtbStoreType.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			CtbStoreType.class
		};
	private long _store_type_id;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _store_type_code;
	private String _store_type_name;
	private String _status;
	private String _originalStatus;
	private long _columnBitmask;
	private CtbStoreType _escapedModel;
}