/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.bmq.vn.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.bmq.vn.model.MtbStoreUser;
import com.bmq.vn.model.MtbStoreUserModel;
import com.bmq.vn.model.MtbStoreUserSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the MtbStoreUser service. Represents a row in the &quot;mtb_store_user&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link MtbStoreUserModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MtbStoreUserImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MtbStoreUserImpl
 * @see MtbStoreUser
 * @see MtbStoreUserModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class MtbStoreUserModelImpl extends BaseModelImpl<MtbStoreUser>
	implements MtbStoreUserModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a mtb store user model instance should use the {@link MtbStoreUser} interface instead.
	 */
	public static final String TABLE_NAME = "mtb_store_user";
	public static final Object[][] TABLE_COLUMNS = {
			{ "store_user_id", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "store_id", Types.BIGINT },
			{ "manage_username", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("store_user_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("store_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("manage_username", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table mtb_store_user (store_user_id LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,store_id LONG,manage_username VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table mtb_store_user";
	public static final String ORDER_BY_JPQL = " ORDER BY mtbStoreUser.store_user_id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY mtb_store_user.store_user_id ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.bmq.vn.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.bmq.vn.model.MtbStoreUser"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.bmq.vn.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.bmq.vn.model.MtbStoreUser"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static MtbStoreUser toModel(MtbStoreUserSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		MtbStoreUser model = new MtbStoreUserImpl();

		model.setStore_user_id(soapModel.getStore_user_id());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setStore_id(soapModel.getStore_id());
		model.setManage_username(soapModel.getManage_username());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<MtbStoreUser> toModels(MtbStoreUserSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<MtbStoreUser> models = new ArrayList<MtbStoreUser>(soapModels.length);

		for (MtbStoreUserSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.bmq.vn.service.util.ServiceProps.get(
				"lock.expiration.time.com.bmq.vn.model.MtbStoreUser"));

	public MtbStoreUserModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _store_user_id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setStore_user_id(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _store_user_id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return MtbStoreUser.class;
	}

	@Override
	public String getModelClassName() {
		return MtbStoreUser.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("store_user_id", getStore_user_id());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("store_id", getStore_id());
		attributes.put("manage_username", getManage_username());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long store_user_id = (Long)attributes.get("store_user_id");

		if (store_user_id != null) {
			setStore_user_id(store_user_id);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long store_id = (Long)attributes.get("store_id");

		if (store_id != null) {
			setStore_id(store_id);
		}

		String manage_username = (String)attributes.get("manage_username");

		if (manage_username != null) {
			setManage_username(manage_username);
		}
	}

	@JSON
	@Override
	public long getStore_user_id() {
		return _store_user_id;
	}

	@Override
	public void setStore_user_id(long store_user_id) {
		_store_user_id = store_user_id;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return StringPool.BLANK;
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getStore_id() {
		return _store_id;
	}

	@Override
	public void setStore_id(long store_id) {
		_store_id = store_id;
	}

	@JSON
	@Override
	public String getManage_username() {
		if (_manage_username == null) {
			return StringPool.BLANK;
		}
		else {
			return _manage_username;
		}
	}

	@Override
	public void setManage_username(String manage_username) {
		_manage_username = manage_username;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			MtbStoreUser.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public MtbStoreUser toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (MtbStoreUser)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		MtbStoreUserImpl mtbStoreUserImpl = new MtbStoreUserImpl();

		mtbStoreUserImpl.setStore_user_id(getStore_user_id());
		mtbStoreUserImpl.setCompanyId(getCompanyId());
		mtbStoreUserImpl.setUserId(getUserId());
		mtbStoreUserImpl.setUserName(getUserName());
		mtbStoreUserImpl.setCreateDate(getCreateDate());
		mtbStoreUserImpl.setModifiedDate(getModifiedDate());
		mtbStoreUserImpl.setStore_id(getStore_id());
		mtbStoreUserImpl.setManage_username(getManage_username());

		mtbStoreUserImpl.resetOriginalValues();

		return mtbStoreUserImpl;
	}

	@Override
	public int compareTo(MtbStoreUser mtbStoreUser) {
		long primaryKey = mtbStoreUser.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof MtbStoreUser)) {
			return false;
		}

		MtbStoreUser mtbStoreUser = (MtbStoreUser)obj;

		long primaryKey = mtbStoreUser.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		MtbStoreUserModelImpl mtbStoreUserModelImpl = this;

		mtbStoreUserModelImpl._setModifiedDate = false;
	}

	@Override
	public CacheModel<MtbStoreUser> toCacheModel() {
		MtbStoreUserCacheModel mtbStoreUserCacheModel = new MtbStoreUserCacheModel();

		mtbStoreUserCacheModel.store_user_id = getStore_user_id();

		mtbStoreUserCacheModel.companyId = getCompanyId();

		mtbStoreUserCacheModel.userId = getUserId();

		mtbStoreUserCacheModel.userName = getUserName();

		String userName = mtbStoreUserCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			mtbStoreUserCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			mtbStoreUserCacheModel.createDate = createDate.getTime();
		}
		else {
			mtbStoreUserCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			mtbStoreUserCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			mtbStoreUserCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		mtbStoreUserCacheModel.store_id = getStore_id();

		mtbStoreUserCacheModel.manage_username = getManage_username();

		String manage_username = mtbStoreUserCacheModel.manage_username;

		if ((manage_username != null) && (manage_username.length() == 0)) {
			mtbStoreUserCacheModel.manage_username = null;
		}

		return mtbStoreUserCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(17);

		sb.append("{store_user_id=");
		sb.append(getStore_user_id());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", store_id=");
		sb.append(getStore_id());
		sb.append(", manage_username=");
		sb.append(getManage_username());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(28);

		sb.append("<model><model-name>");
		sb.append("com.bmq.vn.model.MtbStoreUser");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>store_user_id</column-name><column-value><![CDATA[");
		sb.append(getStore_user_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>store_id</column-name><column-value><![CDATA[");
		sb.append(getStore_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>manage_username</column-name><column-value><![CDATA[");
		sb.append(getManage_username());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = MtbStoreUser.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			MtbStoreUser.class
		};
	private long _store_user_id;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _store_id;
	private String _manage_username;
	private MtbStoreUser _escapedModel;
}